name: havic_env
channels:
  - conda-forge
  - bioconda
  - r
  - defaults

dependencies:
  - python==3.9.0
  - r-base==4.0.3
  - minimap2==2.17
  - graphviz==2.42.3
  - iqtree==2.0.3
  - imagemagick==7.0.10_28
  - clusterpicker==1.2.5
  - samtools==1.11
  - r-rcpp==1.0.5
  - r-magick==2.5.0
  - r-phytools==0.7_70
  - r-pheatmap==1.0.12
  - r-colorspace==1.4_1
  - r-tidyverse==1.3.0
  - bioconductor-biostrings==2.56.0
  - bioconductor-rsamtools==2.4.0
  - bioconductor-ggtree==2.2.1
  - bioconductor-genomicalignments==1.24.0
  - pip==20.2.4
  - pip:
    - '-e .' # developer mode install of havic
