name: havic_env
channels:
  - conda-forge
  - bioconda
  - r
  - defaults

dependencies:
  - python>=3.8
  - ruffus
  - R
  - minimap2
  - iqtree
  - clusterpicker
  - pre-commit
  - flake8
  - samtools
  - pip
  - pip:
    - git+https://github.com/schultzm/havic.git
    - pylint
