name: havic_env
channels:
  - conda-forge
  - bioconda
  - r
  - defaults

dependencies:
  - python>=3.8
  - R
  - minimap2
  - graphviz # trying this
  - iqtree
  - imagemagick
  - clusterpicker
  - pre-commit
  - flake8
  - samtools
  - bioconductor-genomicalignments
  - r-rcpp
  - r-magick
  - r-phytools
  - r-pheatmap
  - r-colorspace
#  - r-BiocManager
  - bioconductor-genomicalignments
  - bioconductor-biostrings
  - bioconductor-rsamtools
  - bioconductor-ggtree
  - bioconductor-tidyverse
  - pip
  - pip:
    - -e . # developer mode install of havic
    - pylint
