name: havic_env
channels:
  - conda-forge
  - bioconda
  - r
  - defaults

dependencies:
  - python=3.8
  - R
  - minimap2
  - iqtree
  - clusterpicker
  - which
  - graphviz
  - samtools
  - pip
  - pip:
    - git+https://github.com/schultzm/HAVIC.git