name: havic_env
channels:
  - conda-forge
  - bioconda
  - r
  - defaults

dependencies:
  - python
  - R
  - minimap2
  - graphviz # trying this
  - iqtree
  - imagemagick
  - clusterpicker
  - pre-commit
  - flake8
  - samtools
  - pip
  - pip:
    - -e . # developer mode install of havic
