version: 2.1

jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/havic
    steps:
      - checkout
      - run: |
          chmod +x install.sh
          . install.sh