version: 2.1

jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/havic
    steps:
      - checkout
      - run: |
          export PATH=${PATH}:/bin:/usr/bin:/sbin:/usr/sbin
          conda clean --all --force-pkgs-dirs
          conda update conda
          conda env create --force --file environment.yml
          conda init bash
          source ~/.bashrc
          conda activate havic_env
          arr=(hav_amplicon hav_wgs hav_pmc measles_wgs hiv_amplicon)
          for i in ${arr[@]}
            do
              havic test ${i}
            done
