version: 2.1

jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/havic
    steps:
      - checkout
      - run: |
          conda env create -f environment.yml
          conda init bash
          source ~/.bashrc
          conda activate havic_env
          conda list
          havic test hav_amplicon
          havic test hav_wgs
          havic test measles_wgs
