version: 2.1

jobs:
  build:
    docker:
      - image: continuumio/miniconda3
      # - image: rackspacedot/python38

    working_directory: ~/HAVIC
    steps:
      - checkout
      - run: |
          conda env create -f environment.yml

      - run: |
          conda init
          source ~/.bashrc
          conda activate havic_env
          export PATH=$PATH:$CONDA_PREFIX
          echo "conda list" && conda list
          echo "PATH" && echo $PATH
          echo "env" && env
          echo "CONDA_PREFIX" && echo $CONDA_PREFIX
          which clusterpicker
          #          export PATH=$PATH:$CONDA_PREFIX #:/home/circleci/.local/bin

          #export PATH=/bin:/usr/bin
          #. $HOME/miniconda3/etc/profile.d/conda.sh
          # conda init
          # source ~/.bashrc
          # conda activate havic_env
          #pip install git+https://github.com/schultzm/HAVIC.git --user
          # echo "install.packages('BiocManager', repos='https://cran.ms.unimelb.edu.au/')
          # BiocManager::install('GenomicAlignments')
          # BiocManager::install('Biostrings')
          # BiocManager::install('Rsamtools')
          # BiocManager::install('ggtree')
          # BiocManager::install('tidyverse')
          # install.packages('Rcpp', repos='https://cloud.r-project.org')
          # install.packages('phytools',repos='https://cloud.r-project.org', type='source') " | R --no-save
          # havic test